### ISSUE TITLE
Lecture 12 — Software Licensing / Review

### ISSUE THREAD

**Issue by HenrikEriksson1** [AronKG/Group-1#102]
- [x] create an issue titled "Lecture 12 checklist" to track these checklist items
- [x] Project has a software license
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [x] [Optional] Present your project at the Lab session on 2 March. (something simple: 5 to 10 minutes)

**Comment by rudymatela** [comment]
The checklist items for this lecture seem to be complete.  :-)   Good job!
